apiVersion: apps/v1
kind: Deployment
metadata:
  name: webjet-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webjet-frontend
  template:
    metadata:
      labels:
        app: webjet-frontend
    spec:
      containers:
        - name: webjet-frontend
          image: webjetregistry.azurecr.io/webjet-frontend:v1
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://4.254.53.10"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: webjet-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: webjet-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
