trigger:
- main

pool:
  name: 'Webjet fullstack'  

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'webjet-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name webjetregistry
