trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/*
      - backend/*
      - k8s/*

pool:
  name: Webjet fullstack

steps:
  # 🔹 Login to Azure and authenticate with Service Principal
  - task: AzureCLI@2
    displayName: "Login to Azure"
    inputs:
      azureSubscription: "webjet-connection"
      scriptType: "powershell"
      scriptLocation: "inlineScript"
      inlineScript: |
        az login --service-principal -u "$(clientId)" -p "$(clientSecret)" --tenant "$(tenantId)"
        az account set --subscription "$(subscriptionId)"
        az aks get-credentials --resource-group webjetResourceGroup --name webjetAKS
        kubectl get pods  # Verify AKS connection

  # 🔹 Build and Push Frontend Docker Image to ACR
  - task: Docker@2
    displayName: "Build and Push Frontend Docker Image"
    inputs:
      command: "buildAndPush"
      repository: "webjetregistry.azurecr.io/webjet-frontend"
      dockerfile: "frontend/Dockerfile"
      containerRegistry: "webjet-acr-connection"
      tags: |
        latest
        $(Build.SourceVersion)  # Adding commit hash as an additional tag for tracking

  # 🔹 Deploy Frontend to AKS and restart the deployment
  - task: Kubernetes@1
    displayName: "Deploy Frontend to AKS"
    inputs:
      connectionType: "Azure Resource Manager"
      azureSubscription: "webjet-connection"
      kubernetesCluster: "webjet-aks"
      namespace: "default"
      command: "apply"
      useConfigurationFile: true
      configuration: "k8s/frontend-deployment.yaml"

  - script: |
      kubectl rollout restart deployment webjet-frontend
    displayName: "Restart Frontend Deployment"

  # 🔹 Build and Push Backend Docker Image to ACR
  - task: Docker@2
    displayName: "Build and Push Backend Docker Image"
    inputs:
      command: "buildAndPush"
      repository: "webjetregistry.azurecr.io/webjet-backend"
      dockerfile: "backend/Dockerfile"
      containerRegistry: "webjet-acr-connection"
      tags: |
        latest
        $(Build.SourceVersion)

  # 🔹 Deploy Backend to AKS and restart the deployment
  - task: Kubernetes@1
    displayName: "Deploy Backend to AKS"
    inputs:
      connectionType: "Azure Resource Manager"
      azureSubscription: "webjet-connection"
      kubernetesCluster: "webjet-aks"
      namespace: "default"
      command: "apply"
      useConfigurationFile: true
      configuration: "k8s/backend-deployment.yaml"

  - script: |
      kubectl rollout restart deployment webjet-backend
    displayName: "Restart Backend Deployment"
