trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/*
      - backend/*
      - k8s/*

pool:
  name: Webjet fullstack

variables:
  - group: Webjet-Deployment-Variables

steps:
  - task: AzureCLI@2
    displayName: "Login to Azure"
    inputs:
      azureSubscription: "webjet-connection"
      scriptType: "powershell"
      scriptLocation: "inlineScript"
      inlineScript: |
        az login --service-principal -u "$(clientId)" -p "$(clientSecret)" --tenant "$(tenantId)"
        az account set --subscription "$(subscriptionId)"
        az aks get-credentials --resource-group webjetResourceGroup --name webjetAKS
        kubectl get pods

  - task: Docker@2
    displayName: "Build and Push Frontend Docker Image"
    inputs:
      command: "buildAndPush"
      repository: "$(containerRegistry)/webjet-frontend"
      dockerfile: "frontend/Dockerfile"
      containerRegistry: "webjet-acr-connection"
      tags: |
        latest
        $(Build.SourceVersion)

  - task: KubernetesManifest@1
    displayName: "Deploy Frontend to AKS"
    inputs:
      action: deploy
      kubernetesServiceConnection: "webjet-connection"
      namespace: "default"
      manifests: "k8s/frontend-deployment.yaml"

  - script: |
      kubectl rollout restart deployment webjet-frontend
    displayName: "Restart Frontend Deployment"

  - task: Docker@2
    displayName: "Build and Push Backend Docker Image"
    inputs:
      command: "buildAndPush"
      repository: "$(containerRegistry)/webjet-backend"
      dockerfile: "backend/Dockerfile"
      containerRegistry: "webjet-acr-connection"
      tags: |
        latest
        $(Build.SourceVersion)

  - task: KubernetesManifest@1
    displayName: "Deploy Backend to AKS"
    inputs:
      action: deploy
      kubernetesServiceConnection: "webjet-connection"
      namespace: "default"
      manifests: "k8s/backend-deployment.yaml"

  - script: |
      kubectl rollout restart deployment webjet-backend
    displayName: "Restart Backend Deployment"
