apiVersion: apps/v1
kind: Deployment
metadata:
  name: webjet-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webjet-frontend
  template:
    metadata:
      labels:
        app: webjet-frontend
    spec:
      containers:
        - name: webjet-frontend
          image: webjetregistry.azurecr.io/webjet-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webjet-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: webjet-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
